// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type Comment struct {
	ID       int        `json:"id"`
	PostID   int        `json:"postId"`
	ParentID *int       `json:"parentId,omitempty"`
	Content  string     `json:"content"`
	Comments []*Comment `json:"comments,omitempty"`
}

type CreateCommentInput struct {
	PostID   int    `json:"postID"`
	ParentID *int   `json:"parentId,omitempty"`
	Content  string `json:"content"`
}

type CreatePostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type Post struct {
	PostData *PostData  `json:"postData,omitempty"`
	Comments []*Comment `json:"comments"`
}

type PostData struct {
	ID            int    `json:"id"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	AllowComments bool   `json:"allowComments"`
}

type Query struct {
}

type Subscription struct {
}
