services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - postgres 
    # networks:
    #   - app_network

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    user: ${POSTGRES_USER}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # networks:
    #   - app_network

volumes:
  postgres-data:

# networks:
#   app_network:
#     name: app_network
#     external: true