services:
  postgres:
      image: postgres:16
      container_name: postgres
      volumes:
        - 'postgres-data:/var/lib/postgresql/data'
      ports:
        - '${POSTGRES_PORT}:${POSTGRES_PORT}'
      user: ${POSTGRES_USER}
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-data: