// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Comment struct {
	ID       string     `json:"id"`
	PostID   string     `json:"postId"`
	ParentID *string    `json:"parentId,omitempty"`
	Text     string     `json:"text"`
	Comments []*Comment `json:"comments,omitempty"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentId,omitempty"`
	Text     string  `json:"text"`
}

type CreatePostInput struct {
	Title           string `json:"title"`
	Content         string `json:"content"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type GetPostInput struct {
	ID       string `json:"id"`
	Page     *int   `json:"page,omitempty"`
	PageSize *int   `json:"pageSize,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Content        string     `json:"content"`
	CommetsAllowed bool       `json:"commetsAllowed"`
	Comments       []*Comment `json:"comments,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
